################################################################################
# Automatically-generated file. Do not edit!
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
../lib/SDL2-2.0.9/test/checkkeys.c \
../lib/SDL2-2.0.9/test/controllermap.c \
../lib/SDL2-2.0.9/test/loopwave.c \
../lib/SDL2-2.0.9/test/loopwavequeue.c \
../lib/SDL2-2.0.9/test/testatomic.c \
../lib/SDL2-2.0.9/test/testaudiocapture.c \
../lib/SDL2-2.0.9/test/testaudiohotplug.c \
../lib/SDL2-2.0.9/test/testaudioinfo.c \
../lib/SDL2-2.0.9/test/testautomation.c \
../lib/SDL2-2.0.9/test/testautomation_audio.c \
../lib/SDL2-2.0.9/test/testautomation_clipboard.c \
../lib/SDL2-2.0.9/test/testautomation_events.c \
../lib/SDL2-2.0.9/test/testautomation_hints.c \
../lib/SDL2-2.0.9/test/testautomation_keyboard.c \
../lib/SDL2-2.0.9/test/testautomation_main.c \
../lib/SDL2-2.0.9/test/testautomation_mouse.c \
../lib/SDL2-2.0.9/test/testautomation_pixels.c \
../lib/SDL2-2.0.9/test/testautomation_platform.c \
../lib/SDL2-2.0.9/test/testautomation_rect.c \
../lib/SDL2-2.0.9/test/testautomation_render.c \
../lib/SDL2-2.0.9/test/testautomation_rwops.c \
../lib/SDL2-2.0.9/test/testautomation_sdltest.c \
../lib/SDL2-2.0.9/test/testautomation_stdlib.c \
../lib/SDL2-2.0.9/test/testautomation_surface.c \
../lib/SDL2-2.0.9/test/testautomation_syswm.c \
../lib/SDL2-2.0.9/test/testautomation_timer.c \
../lib/SDL2-2.0.9/test/testautomation_video.c \
../lib/SDL2-2.0.9/test/testbounds.c \
../lib/SDL2-2.0.9/test/testcustomcursor.c \
../lib/SDL2-2.0.9/test/testdisplayinfo.c \
../lib/SDL2-2.0.9/test/testdraw2.c \
../lib/SDL2-2.0.9/test/testdrawchessboard.c \
../lib/SDL2-2.0.9/test/testdropfile.c \
../lib/SDL2-2.0.9/test/testerror.c \
../lib/SDL2-2.0.9/test/testfile.c \
../lib/SDL2-2.0.9/test/testfilesystem.c \
../lib/SDL2-2.0.9/test/testgamecontroller.c \
../lib/SDL2-2.0.9/test/testgesture.c \
../lib/SDL2-2.0.9/test/testgl2.c \
../lib/SDL2-2.0.9/test/testgles.c \
../lib/SDL2-2.0.9/test/testgles2.c \
../lib/SDL2-2.0.9/test/testhaptic.c \
../lib/SDL2-2.0.9/test/testhittesting.c \
../lib/SDL2-2.0.9/test/testhotplug.c \
../lib/SDL2-2.0.9/test/testiconv.c \
../lib/SDL2-2.0.9/test/testime.c \
../lib/SDL2-2.0.9/test/testintersections.c \
../lib/SDL2-2.0.9/test/testjoystick.c \
../lib/SDL2-2.0.9/test/testkeys.c \
../lib/SDL2-2.0.9/test/testloadso.c \
../lib/SDL2-2.0.9/test/testlock.c \
../lib/SDL2-2.0.9/test/testmessage.c \
../lib/SDL2-2.0.9/test/testmultiaudio.c \
../lib/SDL2-2.0.9/test/testnative.c \
../lib/SDL2-2.0.9/test/testnativew32.c \
../lib/SDL2-2.0.9/test/testnativex11.c \
../lib/SDL2-2.0.9/test/testoverlay2.c \
../lib/SDL2-2.0.9/test/testplatform.c \
../lib/SDL2-2.0.9/test/testpower.c \
../lib/SDL2-2.0.9/test/testqsort.c \
../lib/SDL2-2.0.9/test/testrelative.c \
../lib/SDL2-2.0.9/test/testrendercopyex.c \
../lib/SDL2-2.0.9/test/testrendertarget.c \
../lib/SDL2-2.0.9/test/testresample.c \
../lib/SDL2-2.0.9/test/testrumble.c \
../lib/SDL2-2.0.9/test/testscale.c \
../lib/SDL2-2.0.9/test/testsem.c \
../lib/SDL2-2.0.9/test/testsensor.c \
../lib/SDL2-2.0.9/test/testshader.c \
../lib/SDL2-2.0.9/test/testshape.c \
../lib/SDL2-2.0.9/test/testsprite2.c \
../lib/SDL2-2.0.9/test/testspriteminimal.c \
../lib/SDL2-2.0.9/test/teststreaming.c \
../lib/SDL2-2.0.9/test/testthread.c \
../lib/SDL2-2.0.9/test/testtimer.c \
../lib/SDL2-2.0.9/test/testver.c \
../lib/SDL2-2.0.9/test/testviewport.c \
../lib/SDL2-2.0.9/test/testvulkan.c \
../lib/SDL2-2.0.9/test/testwm2.c \
../lib/SDL2-2.0.9/test/testyuv.c \
../lib/SDL2-2.0.9/test/testyuv_cvt.c \
../lib/SDL2-2.0.9/test/torturethread.c 

OBJS += \
./lib/SDL2-2.0.9/test/checkkeys.o \
./lib/SDL2-2.0.9/test/controllermap.o \
./lib/SDL2-2.0.9/test/loopwave.o \
./lib/SDL2-2.0.9/test/loopwavequeue.o \
./lib/SDL2-2.0.9/test/testatomic.o \
./lib/SDL2-2.0.9/test/testaudiocapture.o \
./lib/SDL2-2.0.9/test/testaudiohotplug.o \
./lib/SDL2-2.0.9/test/testaudioinfo.o \
./lib/SDL2-2.0.9/test/testautomation.o \
./lib/SDL2-2.0.9/test/testautomation_audio.o \
./lib/SDL2-2.0.9/test/testautomation_clipboard.o \
./lib/SDL2-2.0.9/test/testautomation_events.o \
./lib/SDL2-2.0.9/test/testautomation_hints.o \
./lib/SDL2-2.0.9/test/testautomation_keyboard.o \
./lib/SDL2-2.0.9/test/testautomation_main.o \
./lib/SDL2-2.0.9/test/testautomation_mouse.o \
./lib/SDL2-2.0.9/test/testautomation_pixels.o \
./lib/SDL2-2.0.9/test/testautomation_platform.o \
./lib/SDL2-2.0.9/test/testautomation_rect.o \
./lib/SDL2-2.0.9/test/testautomation_render.o \
./lib/SDL2-2.0.9/test/testautomation_rwops.o \
./lib/SDL2-2.0.9/test/testautomation_sdltest.o \
./lib/SDL2-2.0.9/test/testautomation_stdlib.o \
./lib/SDL2-2.0.9/test/testautomation_surface.o \
./lib/SDL2-2.0.9/test/testautomation_syswm.o \
./lib/SDL2-2.0.9/test/testautomation_timer.o \
./lib/SDL2-2.0.9/test/testautomation_video.o \
./lib/SDL2-2.0.9/test/testbounds.o \
./lib/SDL2-2.0.9/test/testcustomcursor.o \
./lib/SDL2-2.0.9/test/testdisplayinfo.o \
./lib/SDL2-2.0.9/test/testdraw2.o \
./lib/SDL2-2.0.9/test/testdrawchessboard.o \
./lib/SDL2-2.0.9/test/testdropfile.o \
./lib/SDL2-2.0.9/test/testerror.o \
./lib/SDL2-2.0.9/test/testfile.o \
./lib/SDL2-2.0.9/test/testfilesystem.o \
./lib/SDL2-2.0.9/test/testgamecontroller.o \
./lib/SDL2-2.0.9/test/testgesture.o \
./lib/SDL2-2.0.9/test/testgl2.o \
./lib/SDL2-2.0.9/test/testgles.o \
./lib/SDL2-2.0.9/test/testgles2.o \
./lib/SDL2-2.0.9/test/testhaptic.o \
./lib/SDL2-2.0.9/test/testhittesting.o \
./lib/SDL2-2.0.9/test/testhotplug.o \
./lib/SDL2-2.0.9/test/testiconv.o \
./lib/SDL2-2.0.9/test/testime.o \
./lib/SDL2-2.0.9/test/testintersections.o \
./lib/SDL2-2.0.9/test/testjoystick.o \
./lib/SDL2-2.0.9/test/testkeys.o \
./lib/SDL2-2.0.9/test/testloadso.o \
./lib/SDL2-2.0.9/test/testlock.o \
./lib/SDL2-2.0.9/test/testmessage.o \
./lib/SDL2-2.0.9/test/testmultiaudio.o \
./lib/SDL2-2.0.9/test/testnative.o \
./lib/SDL2-2.0.9/test/testnativew32.o \
./lib/SDL2-2.0.9/test/testnativex11.o \
./lib/SDL2-2.0.9/test/testoverlay2.o \
./lib/SDL2-2.0.9/test/testplatform.o \
./lib/SDL2-2.0.9/test/testpower.o \
./lib/SDL2-2.0.9/test/testqsort.o \
./lib/SDL2-2.0.9/test/testrelative.o \
./lib/SDL2-2.0.9/test/testrendercopyex.o \
./lib/SDL2-2.0.9/test/testrendertarget.o \
./lib/SDL2-2.0.9/test/testresample.o \
./lib/SDL2-2.0.9/test/testrumble.o \
./lib/SDL2-2.0.9/test/testscale.o \
./lib/SDL2-2.0.9/test/testsem.o \
./lib/SDL2-2.0.9/test/testsensor.o \
./lib/SDL2-2.0.9/test/testshader.o \
./lib/SDL2-2.0.9/test/testshape.o \
./lib/SDL2-2.0.9/test/testsprite2.o \
./lib/SDL2-2.0.9/test/testspriteminimal.o \
./lib/SDL2-2.0.9/test/teststreaming.o \
./lib/SDL2-2.0.9/test/testthread.o \
./lib/SDL2-2.0.9/test/testtimer.o \
./lib/SDL2-2.0.9/test/testver.o \
./lib/SDL2-2.0.9/test/testviewport.o \
./lib/SDL2-2.0.9/test/testvulkan.o \
./lib/SDL2-2.0.9/test/testwm2.o \
./lib/SDL2-2.0.9/test/testyuv.o \
./lib/SDL2-2.0.9/test/testyuv_cvt.o \
./lib/SDL2-2.0.9/test/torturethread.o 

C_DEPS += \
./lib/SDL2-2.0.9/test/checkkeys.d \
./lib/SDL2-2.0.9/test/controllermap.d \
./lib/SDL2-2.0.9/test/loopwave.d \
./lib/SDL2-2.0.9/test/loopwavequeue.d \
./lib/SDL2-2.0.9/test/testatomic.d \
./lib/SDL2-2.0.9/test/testaudiocapture.d \
./lib/SDL2-2.0.9/test/testaudiohotplug.d \
./lib/SDL2-2.0.9/test/testaudioinfo.d \
./lib/SDL2-2.0.9/test/testautomation.d \
./lib/SDL2-2.0.9/test/testautomation_audio.d \
./lib/SDL2-2.0.9/test/testautomation_clipboard.d \
./lib/SDL2-2.0.9/test/testautomation_events.d \
./lib/SDL2-2.0.9/test/testautomation_hints.d \
./lib/SDL2-2.0.9/test/testautomation_keyboard.d \
./lib/SDL2-2.0.9/test/testautomation_main.d \
./lib/SDL2-2.0.9/test/testautomation_mouse.d \
./lib/SDL2-2.0.9/test/testautomation_pixels.d \
./lib/SDL2-2.0.9/test/testautomation_platform.d \
./lib/SDL2-2.0.9/test/testautomation_rect.d \
./lib/SDL2-2.0.9/test/testautomation_render.d \
./lib/SDL2-2.0.9/test/testautomation_rwops.d \
./lib/SDL2-2.0.9/test/testautomation_sdltest.d \
./lib/SDL2-2.0.9/test/testautomation_stdlib.d \
./lib/SDL2-2.0.9/test/testautomation_surface.d \
./lib/SDL2-2.0.9/test/testautomation_syswm.d \
./lib/SDL2-2.0.9/test/testautomation_timer.d \
./lib/SDL2-2.0.9/test/testautomation_video.d \
./lib/SDL2-2.0.9/test/testbounds.d \
./lib/SDL2-2.0.9/test/testcustomcursor.d \
./lib/SDL2-2.0.9/test/testdisplayinfo.d \
./lib/SDL2-2.0.9/test/testdraw2.d \
./lib/SDL2-2.0.9/test/testdrawchessboard.d \
./lib/SDL2-2.0.9/test/testdropfile.d \
./lib/SDL2-2.0.9/test/testerror.d \
./lib/SDL2-2.0.9/test/testfile.d \
./lib/SDL2-2.0.9/test/testfilesystem.d \
./lib/SDL2-2.0.9/test/testgamecontroller.d \
./lib/SDL2-2.0.9/test/testgesture.d \
./lib/SDL2-2.0.9/test/testgl2.d \
./lib/SDL2-2.0.9/test/testgles.d \
./lib/SDL2-2.0.9/test/testgles2.d \
./lib/SDL2-2.0.9/test/testhaptic.d \
./lib/SDL2-2.0.9/test/testhittesting.d \
./lib/SDL2-2.0.9/test/testhotplug.d \
./lib/SDL2-2.0.9/test/testiconv.d \
./lib/SDL2-2.0.9/test/testime.d \
./lib/SDL2-2.0.9/test/testintersections.d \
./lib/SDL2-2.0.9/test/testjoystick.d \
./lib/SDL2-2.0.9/test/testkeys.d \
./lib/SDL2-2.0.9/test/testloadso.d \
./lib/SDL2-2.0.9/test/testlock.d \
./lib/SDL2-2.0.9/test/testmessage.d \
./lib/SDL2-2.0.9/test/testmultiaudio.d \
./lib/SDL2-2.0.9/test/testnative.d \
./lib/SDL2-2.0.9/test/testnativew32.d \
./lib/SDL2-2.0.9/test/testnativex11.d \
./lib/SDL2-2.0.9/test/testoverlay2.d \
./lib/SDL2-2.0.9/test/testplatform.d \
./lib/SDL2-2.0.9/test/testpower.d \
./lib/SDL2-2.0.9/test/testqsort.d \
./lib/SDL2-2.0.9/test/testrelative.d \
./lib/SDL2-2.0.9/test/testrendercopyex.d \
./lib/SDL2-2.0.9/test/testrendertarget.d \
./lib/SDL2-2.0.9/test/testresample.d \
./lib/SDL2-2.0.9/test/testrumble.d \
./lib/SDL2-2.0.9/test/testscale.d \
./lib/SDL2-2.0.9/test/testsem.d \
./lib/SDL2-2.0.9/test/testsensor.d \
./lib/SDL2-2.0.9/test/testshader.d \
./lib/SDL2-2.0.9/test/testshape.d \
./lib/SDL2-2.0.9/test/testsprite2.d \
./lib/SDL2-2.0.9/test/testspriteminimal.d \
./lib/SDL2-2.0.9/test/teststreaming.d \
./lib/SDL2-2.0.9/test/testthread.d \
./lib/SDL2-2.0.9/test/testtimer.d \
./lib/SDL2-2.0.9/test/testver.d \
./lib/SDL2-2.0.9/test/testviewport.d \
./lib/SDL2-2.0.9/test/testvulkan.d \
./lib/SDL2-2.0.9/test/testwm2.d \
./lib/SDL2-2.0.9/test/testyuv.d \
./lib/SDL2-2.0.9/test/testyuv_cvt.d \
./lib/SDL2-2.0.9/test/torturethread.d 


# Each subdirectory must supply rules for building sources it contributes
lib/SDL2-2.0.9/test/%.o: ../lib/SDL2-2.0.9/test/%.c
	@echo 'Building file: $<'
	@echo 'Invoking: GCC C Compiler'
	gcc -O0 -g3 -Wall -c -fmessage-length=0 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@)" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '


