################################################################################
# Automatically-generated file. Do not edit!
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
O_SRCS += \
../lib/SDL2/SDL.o \
../lib/SDL2/SDL_RLEaccel.o \
../lib/SDL2/SDL_assert.o \
../lib/SDL2/SDL_atomic.o \
../lib/SDL2/SDL_audio.o \
../lib/SDL2/SDL_audiocvt.o \
../lib/SDL2/SDL_audiodev.o \
../lib/SDL2/SDL_audiotypecvt.o \
../lib/SDL2/SDL_blendfillrect.o \
../lib/SDL2/SDL_blendline.o \
../lib/SDL2/SDL_blendpoint.o \
../lib/SDL2/SDL_blit.o \
../lib/SDL2/SDL_blit_0.o \
../lib/SDL2/SDL_blit_1.o \
../lib/SDL2/SDL_blit_A.o \
../lib/SDL2/SDL_blit_N.o \
../lib/SDL2/SDL_blit_auto.o \
../lib/SDL2/SDL_blit_copy.o \
../lib/SDL2/SDL_blit_slow.o \
../lib/SDL2/SDL_bmp.o \
../lib/SDL2/SDL_clipboard.o \
../lib/SDL2/SDL_clipboardevents.o \
../lib/SDL2/SDL_cocoaclipboard.o \
../lib/SDL2/SDL_cocoaevents.o \
../lib/SDL2/SDL_cocoakeyboard.o \
../lib/SDL2/SDL_cocoamessagebox.o \
../lib/SDL2/SDL_cocoametalview.o \
../lib/SDL2/SDL_cocoamodes.o \
../lib/SDL2/SDL_cocoamouse.o \
../lib/SDL2/SDL_cocoamousetap.o \
../lib/SDL2/SDL_cocoaopengl.o \
../lib/SDL2/SDL_cocoaopengles.o \
../lib/SDL2/SDL_cocoashape.o \
../lib/SDL2/SDL_cocoavideo.o \
../lib/SDL2/SDL_cocoavulkan.o \
../lib/SDL2/SDL_cocoawindow.o \
../lib/SDL2/SDL_coreaudio.o \
../lib/SDL2/SDL_cpuinfo.o \
../lib/SDL2/SDL_d3dmath.o \
../lib/SDL2/SDL_dataqueue.o \
../lib/SDL2/SDL_diskaudio.o \
../lib/SDL2/SDL_displayevents.o \
../lib/SDL2/SDL_drawline.o \
../lib/SDL2/SDL_drawpoint.o \
../lib/SDL2/SDL_dropevents.o \
../lib/SDL2/SDL_dummy_main.o \
../lib/SDL2/SDL_dummyaudio.o \
../lib/SDL2/SDL_dummysensor.o \
../lib/SDL2/SDL_dynapi.o \
../lib/SDL2/SDL_egl.o \
../lib/SDL2/SDL_error.o \
../lib/SDL2/SDL_events.o \
../lib/SDL2/SDL_fillrect.o \
../lib/SDL2/SDL_gamecontroller.o \
../lib/SDL2/SDL_gesture.o \
../lib/SDL2/SDL_getenv.o \
../lib/SDL2/SDL_haptic.o \
../lib/SDL2/SDL_hidapi_ps4.o \
../lib/SDL2/SDL_hidapi_switch.o \
../lib/SDL2/SDL_hidapi_xbox360.o \
../lib/SDL2/SDL_hidapi_xboxone.o \
../lib/SDL2/SDL_hidapijoystick.o \
../lib/SDL2/SDL_hints.o \
../lib/SDL2/SDL_iconv.o \
../lib/SDL2/SDL_joystick.o \
../lib/SDL2/SDL_keyboard.o \
../lib/SDL2/SDL_log.o \
../lib/SDL2/SDL_malloc.o \
../lib/SDL2/SDL_mixer.o \
../lib/SDL2/SDL_mouse.o \
../lib/SDL2/SDL_nullevents.o \
../lib/SDL2/SDL_nullframebuffer.o \
../lib/SDL2/SDL_nullvideo.o \
../lib/SDL2/SDL_pixels.o \
../lib/SDL2/SDL_poll.o \
../lib/SDL2/SDL_power.o \
../lib/SDL2/SDL_qsort.o \
../lib/SDL2/SDL_quit.o \
../lib/SDL2/SDL_rect.o \
../lib/SDL2/SDL_render.o \
../lib/SDL2/SDL_render_d3d.o \
../lib/SDL2/SDL_render_d3d11.o \
../lib/SDL2/SDL_render_gl.o \
../lib/SDL2/SDL_render_gles.o \
../lib/SDL2/SDL_render_gles2.o \
../lib/SDL2/SDL_render_metal.o \
../lib/SDL2/SDL_render_psp.o \
../lib/SDL2/SDL_render_sw.o \
../lib/SDL2/SDL_rotate.o \
../lib/SDL2/SDL_rwops.o \
../lib/SDL2/SDL_rwopsbundlesupport.o \
../lib/SDL2/SDL_sensor.o \
../lib/SDL2/SDL_shaders_d3d.o \
../lib/SDL2/SDL_shaders_d3d11.o \
../lib/SDL2/SDL_shaders_gl.o \
../lib/SDL2/SDL_shaders_gles2.o \
../lib/SDL2/SDL_shape.o \
../lib/SDL2/SDL_spinlock.o \
../lib/SDL2/SDL_stdlib.o \
../lib/SDL2/SDL_stretch.o \
../lib/SDL2/SDL_string.o \
../lib/SDL2/SDL_surface.o \
../lib/SDL2/SDL_syscond.o \
../lib/SDL2/SDL_sysfilesystem.o \
../lib/SDL2/SDL_syshaptic.o \
../lib/SDL2/SDL_sysjoystick.o \
../lib/SDL2/SDL_sysloadso.o \
../lib/SDL2/SDL_sysmutex.o \
../lib/SDL2/SDL_syspower.o \
../lib/SDL2/SDL_syssem.o \
../lib/SDL2/SDL_systhread.o \
../lib/SDL2/SDL_systimer.o \
../lib/SDL2/SDL_systls.o \
../lib/SDL2/SDL_test_assert.o \
../lib/SDL2/SDL_test_common.o \
../lib/SDL2/SDL_test_compare.o \
../lib/SDL2/SDL_test_crc32.o \
../lib/SDL2/SDL_test_font.o \
../lib/SDL2/SDL_test_fuzzer.o \
../lib/SDL2/SDL_test_harness.o \
../lib/SDL2/SDL_test_imageBlit.o \
../lib/SDL2/SDL_test_imageBlitBlend.o \
../lib/SDL2/SDL_test_imageFace.o \
../lib/SDL2/SDL_test_imagePrimitives.o \
../lib/SDL2/SDL_test_imagePrimitivesBlend.o \
../lib/SDL2/SDL_test_log.o \
../lib/SDL2/SDL_test_md5.o \
../lib/SDL2/SDL_test_memory.o \
../lib/SDL2/SDL_test_random.o \
../lib/SDL2/SDL_thread.o \
../lib/SDL2/SDL_timer.o \
../lib/SDL2/SDL_touch.o \
../lib/SDL2/SDL_video.o \
../lib/SDL2/SDL_vulkan_utils.o \
../lib/SDL2/SDL_wave.o \
../lib/SDL2/SDL_windowevents.o \
../lib/SDL2/SDL_x11clipboard.o \
../lib/SDL2/SDL_x11dyn.o \
../lib/SDL2/SDL_x11events.o \
../lib/SDL2/SDL_x11framebuffer.o \
../lib/SDL2/SDL_x11keyboard.o \
../lib/SDL2/SDL_x11messagebox.o \
../lib/SDL2/SDL_x11modes.o \
../lib/SDL2/SDL_x11mouse.o \
../lib/SDL2/SDL_x11opengl.o \
../lib/SDL2/SDL_x11opengles.o \
../lib/SDL2/SDL_x11shape.o \
../lib/SDL2/SDL_x11touch.o \
../lib/SDL2/SDL_x11video.o \
../lib/SDL2/SDL_x11vulkan.o \
../lib/SDL2/SDL_x11window.o \
../lib/SDL2/SDL_x11xinput2.o \
../lib/SDL2/SDL_yuv.o \
../lib/SDL2/SDL_yuv_sw.o \
../lib/SDL2/e_atan2.o \
../lib/SDL2/e_exp.o \
../lib/SDL2/e_fmod.o \
../lib/SDL2/e_log.o \
../lib/SDL2/e_log10.o \
../lib/SDL2/e_pow.o \
../lib/SDL2/e_rem_pio2.o \
../lib/SDL2/e_sqrt.o \
../lib/SDL2/edid-parse.o \
../lib/SDL2/hid.o \
../lib/SDL2/imKStoUCS.o \
../lib/SDL2/k_cos.o \
../lib/SDL2/k_rem_pio2.o \
../lib/SDL2/k_sin.o \
../lib/SDL2/k_tan.o \
../lib/SDL2/s_atan.o \
../lib/SDL2/s_copysign.o \
../lib/SDL2/s_cos.o \
../lib/SDL2/s_fabs.o \
../lib/SDL2/s_floor.o \
../lib/SDL2/s_scalbn.o \
../lib/SDL2/s_sin.o \
../lib/SDL2/s_tan.o \
../lib/SDL2/yuv_rgb.o 


# Each subdirectory must supply rules for building sources it contributes

